name: deploy
on: [push, pull_request]
jobs:
  build:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Build app
        run: npm run build
      - name: Publish app artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    name: Run tests
    runs-on: ubuntu-latest

    needs:
      - build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Run tests
        run: npm test
